version: '3.9'

services:
  pal-vs-pokemon-app:
    build:
      context: ../
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:3000'
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: postgres-db
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
